export const ADD_SURVEY = "ADD_SURVEY"
export const SET_ACTIVE_SURVEY = "SET_ACTIVE_SURVEY"
export const UNSET_ACTIVE_SURVEY = "UNSET_ACTIVE_SURVEY"
export const UNSET_ACTIVE_QUESTION = "UNSET_ACTIVE_QUESTION"